# Generated by Django 6.0.2 on 2026-02-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_balance',
        ),
    ]
